### ISSUE TITLE
CT running lint all task

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#17] opened 2019-01-24 00:12 UTC
```
states-of-matter-basics : build : phet
Failure to grunt snapshot-1548281897096/states-of-matter-basics:
Running "lint-all" task

Running "report-media" task
>> missing-file: states-of-matter/images/flame.png
>> missing-file: states-of-matter/images/ice-cube-stack.png
>> missing-file: states-of-matter/images/som-atomic-interactions-icon.png
Fatal error: There is an issue with the licenses for media types.


Approximately 1/23/2019, 3:18:17 PM
```

**Comment by pixelzoom** [comment] 2019-01-24 04:05
Duplicate of phetsims/atomic-interactions#77, closing.

**Closed by pixelzoom** 2019-01-24 04:05 UTC
Labels: type:automated-testing
